use_frameworks!

target 'SKYKitChat_Example' do
  pod 'SKYKitChat', :path => '../'

  target 'SKYKitChat_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end

target 'Swift Example' do
  pod 'SKYKitChat', :path => '../'
  pod 'SKYKit/Core',
    :git => 'https://github.com/SkygearIO/skygear-SDK-iOS.git',
    :commit => '3548482c0d79ae7e991c4fc0b9139de31e7a6917'
  pod 'SKYKitChat/UI', :path => '../'
  pod 'Kingfisher', '~> 3.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
